/*
 * WHY: Version 04 must be driven by the same design-system truths as Business OS instead of scattered page constants.
 * WHAT: Exports canonical tokens, sections, and controls for the DroidMaster Business OS styled website page.
 */

export const systemConfig = {
  storageKey: "droidfleet.voiceDesignSystem.tokens.v5",
  presetStorageKey: "droidfleet.voiceDesignSystem.presets.v1",
  fonts: [
    "Ubuntu",
    "Orbitron",
    "Rajdhani",
    "Audiowide",
    "Aldrich",
    "Exo 2",
    "Chakra Petch",
    "Oxanium",
    "Tektur",
    "Share Tech Mono",
    "Michroma",
    "Electrolize",
    "Saira",
    "Saira Semi Condensed",
    "Tomorrow",
    "Titillium Web",
    "Barlow Condensed",
    "Encode Sans Semi Condensed",
    "Quantico",
    "Jura",
    "Kanit",
    "Syncopate",
    "Zen Dots",
    "Space Grotesk",
    "IBM Plex Mono",
  ],
  titleFonts: [
    "Ubuntu",
    "Exo 2",
    "Saira",
    "Rajdhani",
    "Chakra Petch",
    "Exo 2",
    "Oxanium",
    "Tektur",
    "Titillium Web",
    "Encode Sans Semi Condensed",
    "Saira",
  ],
  tokens: {
    workspacePrimary: { label: "Primary", type: "color", value: "#0d8ece", cssVar: "--voice-workspace-primary" },
    workspaceSecondary: { label: "Secondary", type: "color", value: "#0e0132", cssVar: "--voice-workspace-secondary" },
    graphSecondary: { label: "Graph bottom", type: "color", value: "#2127d4", cssVar: "--voice-graph-secondary" },
    surface: { label: "Surface", type: "color", value: "#000003", cssVar: "--voice-surface" },
    text: { label: "Text", type: "color", value: "#eef4ff", cssVar: "--voice-text" },
    muted: { label: "Muted", type: "color", value: "#97a4b3", cssVar: "--voice-muted" },
    cardBorderWidth: { label: "Card border", type: "number", min: 0, max: 4, value: 0, unit: "px", cssVar: "--voice-card-border-width" },
    cardBorderStrength: { label: "Border strength", type: "range", min: 0, max: 80, value: 70, unit: "%", cssVar: "--voice-card-border-strength" },
    cardBorderColor: { label: "Border color", type: "color", value: "#0f0f10", cssVar: "--voice-card-border-color" },
    cardSurface: { label: "Card color", type: "color", value: "#06090d", cssVar: "--voice-card-surface" },
    cardPadding: { label: "Card padding", type: "number", min: 8, max: 36, value: 16, unit: "px", cssVar: "--voice-card-padding" },
    cardRadius: { label: "Card radius", type: "number", min: 0, max: 18, value: 4, unit: "px", cssVar: "--voice-card-radius" },
    cardBackdropBlur: { label: "Card glass blur", type: "number", min: 0, max: 80, value: 36, unit: "px", cssVar: "--voice-card-backdrop-blur" },
    cardInsetLineWidth: { label: "Inset line", type: "number", min: 0, max: 4, value: 2, unit: "px", cssVar: "--voice-card-inset-line-width" },
    cardInsetLineStrength: { label: "Inset line strength", type: "range", min: 0, max: 90, value: 23, unit: "%", cssVar: "--voice-card-inset-line-strength" },
    cardInsetLineColor: { label: "Inset line color", type: "color", value: "#000000", cssVar: "--voice-card-inset-line-color" },
    cardInsetShadowBlur: { label: "Inset blur", type: "number", min: 0, max: 120, value: 18, unit: "px", cssVar: "--voice-card-inset-shadow-blur" },
    cardInsetShadowStrength: { label: "Inset strength", type: "range", min: 0, max: 90, value: 15, unit: "%", cssVar: "--voice-card-inset-shadow-strength" },
    cardInsetShadowColor: { label: "Inset color", type: "color", value: "#2a2961", cssVar: "--voice-card-inset-shadow-color" },
    cardOutsetShadowBlur: { label: "Outset blur", type: "number", min: 0, max: 140, value: 2, unit: "px", cssVar: "--voice-card-outset-shadow-blur" },
    cardOutsetShadowScale: { label: "Outset spread", type: "range", min: 0, max: 9, value: 0, cssVar: "--voice-card-outset-shadow-scale", transform: "decimal" },
    cardOutsetShadowStrength: { label: "Outset strength", type: "range", min: 0, max: 90, value: 57, unit: "%", cssVar: "--voice-card-outset-shadow-strength" },
    cardOutsetShadowColor: { label: "Outset color", type: "color", value: "#47499a", cssVar: "--voice-card-outset-shadow-color" },
    controlBorderWidth: { label: "Button border", type: "number", min: 0, max: 4, value: 2, unit: "px", cssVar: "--voice-control-border-width" },
    controlBorderStrength: { label: "Button border strength", type: "range", min: 0, max: 90, value: 14, unit: "%", cssVar: "--voice-control-border-strength" },
    controlBorderColor: { label: "Button border color", type: "color", value: "#454545", cssVar: "--voice-control-border-color" },
    insetBlur: { label: "Inset blur", type: "number", min: 0, max: 72, value: 25, unit: "px", cssVar: "--voice-inset-blur", aliases: ["buttonInsetBlur"] },
    insetStrength: { label: "Inset strength", type: "range", min: 0, max: 64, value: 34, unit: "%", cssVar: "--voice-inset-strength", aliases: ["buttonInsetStrength"] },
    insetShadowColor: { label: "Button inset color", type: "color", value: "#0054db", cssVar: "--voice-inset-shadow-color" },
    textSize: { label: "Control text size", type: "number", min: 7, max: 13, value: 9, unit: "px", cssVar: "--voice-text-size", aliases: ["controlTextSize"] },
    fontUi: { label: "Interface font", type: "font", value: "Tektur", cssVar: "--voice-ui-font", fontSet: "fonts" },
    uiTextSize: { label: "Interface size", type: "number", min: 8, max: 16, value: 10, unit: "px", cssVar: "--voice-ui-text-size" },
    fontTitle: { label: "Title font", type: "font", value: "Exo 2", cssVar: "--voice-title-font", fontSet: "titleFonts" },
    titleTextSize: { label: "Title size", type: "number", min: 28, max: 72, value: 63, unit: "px", cssVar: "--voice-title-text-size" },
    fontText: { label: "Body font", type: "font", value: "Ubuntu", cssVar: "--voice-body-font", fontSet: "fonts" },
    bodyTextSize: { label: "Body size", type: "number", min: 12, max: 22, value: 15, unit: "px", cssVar: "--voice-body-text-size" },
    routeShellBorderWidth: { label: "Route shell border", type: "number", min: 0, max: 4, value: 1, unit: "px", cssVar: "--voice-route-shell-border-width" },
    routeShellBorderStrength: { label: "Route shell strength", type: "range", min: 0, max: 80, value: 37, unit: "%", cssVar: "--voice-route-shell-border-strength" },
    routeShellBorderColor: { label: "Route shell color", type: "color", value: "#060b1e", cssVar: "--voice-route-shell-border-color" },
  },
  groups: [
    { title: "Workspace", keys: ["workspacePrimary", "workspaceSecondary", "graphSecondary", "surface", "text", "muted"] },
    { title: "Typography", keys: ["fontUi", "uiTextSize", "fontTitle", "titleTextSize", "fontText", "bodyTextSize"] },
    { title: "Button", keys: ["controlBorderWidth", "controlBorderStrength", "controlBorderColor", "insetBlur", "insetStrength", "insetShadowColor", "textSize"] },
    { title: "Card", keys: ["cardBorderWidth", "cardBorderStrength", "cardBorderColor", "cardSurface", "cardPadding", "cardRadius", "cardBackdropBlur", "cardInsetLineWidth", "cardInsetLineStrength", "cardInsetLineColor", "cardInsetShadowBlur", "cardInsetShadowStrength", "cardInsetShadowColor", "cardOutsetShadowBlur", "cardOutsetShadowScale", "cardOutsetShadowStrength", "cardOutsetShadowColor"] },
    { title: "Page", keys: ["routeShellBorderWidth", "routeShellBorderStrength", "routeShellBorderColor", "surface", "text", "muted"] },
  ],
  references: [
    ["Atlassian", "Foundations cover tokens, accessibility, content, spacing, grid, color, typography, iconography, elevation, and borders."],
    ["Carbon", "Tokens name UI roles so themes can change values without changing component code."],
    ["Material", "Primitives like color, type, and shape compose into reusable components."],
    ["Cloudscape", "Tokens are sub-atomic particles for components and must keep their intended role."],
  ],
  sections: [
    ["spacingGrid", "Foundations", "Spacing & Grid", "Density, gutters, columns, and vertical rhythm for operator surfaces."],
    ["colorThemes", "Brand", "Color Themes", "Role-based palettes that can move without changing component code."],
    ["desktopTypography", "Typography", "Desktop Typography", "Display, heading, body, label, and dense data scales."],
    ["mobileTypography", "Typography", "Mobile Typography", "Compact scales for constrained tools and small surfaces."],
    ["icons", "Assets", "Icons", "Droid and command glyph rules for alignment, hit area, and usage."],
    ["styles", "Themes", "Styles", "Reusable elevation, inset, background, and border treatments."],
    ["buttons", "Forms", "Buttons", "Primary, secondary, neutral, disabled, and compact command behavior."],
    ["inputs", "Forms", "Inputs", "Field states, helper copy, errors, and grouped layouts."],
    ["customInputs", "Forms", "Custom Inputs", "Checkboxes, radios, toggles, steppers, and segmented choices."],
    ["select", "Forms", "Select", "Compact menus and pickers for dense workflows."],
    ["tabs", "Display", "Tabs", "View switching, grouped content, and nested sections."],
    ["miscellaneous", "Display", "Miscellaneous", "Tables, pagination, avatars, chips, tooltips, progress, and dividers."],
    ["popovers", "Display", "Popovers", "Floating panels for detail, transient menus, and contextual actions."],
  ],
};
